### ISSUE TITLE
Incorrectly added lines and enchancement idea

### ISSUE THREAD

**Issue by przemekiljan** [Zymo-Research/figaro#25]
Hello,
I've been trying to use your software but unfortunately in fileNamingStandards.py, newly added file naming standards (I suppose) were added outside of curly brace. I'm referring to lines no. 8,9,159,160. 

Also, for python command the Illumina naming convention isn't a default value. It seems that nononsense is. 

Besides those problems the software seems very useful and adding somehow averaged output would be even more helpful (for more streamlined analyses, where treating each sample with specific parameters might be problematic).

Cheers :robot: 
Edit: Also, how one is supposed to link output line with specific sample when JSON output doesn't have "ID" field, and all the parameter outputs are sorted by score value? Lack of this correspondence makes it really hard to make proper use of this tool, especially when each set of parameters is generated for each separate sample.

**Comment by przemekiljan** [comment]
To commnet on my edit post scriptum - apparently generated parameters list is proposed parameters for one PE read, and not one set per pair of reads in input directory. I thought you could load multiple files into figaro, and in return receive list of best parameters for each PE read. My bad, but considering that input option is directory instead of separate files, I instinctively assumed that it was tool for multiple files analysis.

**Comment by handibles** [comment]
@przemekiljan The point on multiple v single sets of PE reads might explain some of the behaviour below, but does seem strange given figaro's ability to parse a folder full of files and stating that as intended behaviour in the ```README.md``` (under "Command line version"). Can I ask where you saw single samples stated as the intent? 

Good catch also on the ```NoNonsenseNamingStandard``` as default.

Sent a [PR](https://github.com/Zymo-Research/figaro/pull/26) for extra conventions and the possible ```NoNonsenseNamingStandard```naming mismatch above, but two additional snags were (related to PR?):

1. firstly, from 132 ```fastqs```, I get back 118 entries in the ```JSON``` output (```log``` is empty), suggesting some files are silently failing (same run, same naming convention). I would check the missing files, but see 2:
2. as above, no names are appended to the outputs in the ```JSON``` - not sure if this is intended functionality. 

Partially due to 1&2, I'll probably end up taking subjective averages of these objective parameters output - can I ask what is the envisioned next step for e.g. a ```DADA2``` run incorporating this data (esp. in ```JSON```)? Pass values to ```filtAndTrim()``` as a vector of parameters?

As ever Dev, thanks for the time put into this.

**Comment by michael-weinstein** [comment]
Have applied some of the suggestions here and improved the nononsense naming scheme with regular expression tweaks.  I will see about being able to output something directly for going into dada2 in the next version along with a few other upgrades.
