### ISSUE TITLE
Question about the scoring method of FIGARO

### ISSUE THREAD

**Issue by JenYanFan** [Zymo-Research/figaro#28]
Dear Zymo-Research,

I found that FIGARO is a useful tool to determine the trimming and filtering parameters . 
![image](https://user-images.githubusercontent.com/78011809/109785319-f979dc00-7c46-11eb-955b-05a7bcd910e6.png) 
At first glance, I think this formula is a bit similar to Euclidean distance. "EEforward - 1" and "EEreverse - 1" might be related to the description in the manual of Usearch.
> E < 1, then the most probable number of errors is zero. (https://www.drive5.com/usearch/manual/exp_errs.html)

However, I am not familiar with the principle behind the scoring method of FIGARO. Why is "-1" instead of "-0" in the formula? Is there any concept related to the design of the formula?

Thank you very much for your help.
Sincerely,

Jen Yan Fan

**Comment by michael-weinstein** [comment]
The formula is essentially just based upon how much error I would want to tolerate in a read of a given length.  I essentially decided to give a single expected error in a read no penalty (admittedly, I designed this around longer amplicons covering two variable regions where there is essentially no chance of an EE of 0.  So the formula starts off looking at the expected percentage of retained reads through the filter (keeping more reads is generally a good thing), but allowing more errors to enable that level of read retention.  The penalty increases exponentially because you can imagine that a 300 base read with 12 errors in it is more than just 3x as bad as one with 4 errors.  The one with 12 errors would be nearly unusable.

**Comment by JenYanFan** [comment]
Thank you very much.
